name: Cloud Android NDK Build

on:
  push:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        distribution: 'zulu'
        java-version: '17'

    - name: Setup Android NDK
      uses: nttld/setup-ndk@v1
      with:
        ndk-version: r25c
        link-to-sdk: true

    # الخطوة السحرية لإصلاح ملفات الـ Wrapper الناقصة وتوليد الـ Jar تلقائياً
    - name: Regenerate Gradle Wrapper
      run: gradle wrapper

    - name: Make Gradle Executable
      run: chmod +x gradlew

    - name: Compile C++ and Build APK
      run: ./gradlew assembleDebug
      
    - name: Upload Finished APK
      uses: actions/upload-artifact@v4
      with:
        name: FreeFire-ModMenu
        path: app/build/outputs/apk/debug/app-debug.apk
